#!/usr/bin/env ruby

$LOAD_PATH << './'
require 'pathname'
require 'optparse'
require 'bundler'

options = OptionParser.new do |opts|
  opts.banner = <<-EOF
Usage:
  agent_installer [options]
EOF

  opts.on("-v", "--verbose", "Run verbosely") do
    NewRelic::Plugin::Config.config.newrelic['verbose'] = 1
  end

  opts.on("-l", "--license LICENSE_KEY", "Your NewRelic account License Key") do | license_key |
    $license_key = license_key
  end

  opts.on("-h", "--help") do
    puts opts
    if File.basename($0) == File.basename(__FILE__)
      exit 0
    end
  end
end


if ARGV.empty?
  puts options
else
  config_file = File.read(File.expand_path("../config/newrelic_plugin.yml.template", __FILE__))
  if $license_key
    config_file.gsub!("YOUR_LICENSE_KEY_HERE", $license_key)
  end
  require 'fileutils'
  config_path = Pathname.new('config/newrelic_plugin.yml')
  FileUtils.mkdir_p "config"
  if config_path.exist?
    puts "Agent config file #{File.expand_path(config_path)} already exists."
  else
    File.open("config/newrelic_plugin.yml", "w") do | io |
      io.write(config_file)
    end
    puts "Saved agent config file #{File.expand_path(config_path)}"
  end
  system('bundle install')
end

